[[Express]]

> 參考 [官網 Express 錯誤處理 (expressjs.com)](https://expressjs.com/zh-tw/guide/error-handling.html) 方式。

# 補捉程式錯誤
```js
process.on('uncaughtException', err => {
 	// 記錄錯誤下來，等到服務都處理完後，停掉該 process
	console.error('Uncaughted Exception！')
	console.error(err);
	process.exit(1);
});
```

- 針對==同步的錯誤==發生，且未處理時所產生的事件。
- 有關 `process.exit` 可以參考 [官網說明](https://nodejs.org/api/process.html#processexitcode)，如果有設置非 0 的值，則 Node.js 不會終止，直到全部的 `exit` 事件皆被呼叫。
- `process.exit` 的 status code 可以參考 [官網規範](https://nodejs.org/api/process.html#process_exit_codes)。
- ==開始偵聽的位置很重要==，如果監聽於問題發生之後，便無法成功捕捉到錯誤。
- 因為這裡為程式的執行終點站，如果需要關閉資料庫連線，也可以在這裡撰寫。

# 補捉未處理的 catch
```js
// 未捕捉到的 catch 
process.on('unhandledRejection', (reason, promise) => {
  console.error('未捕捉到的 rejection：', promise, '原因：', reason);
  // 記錄於 log 上
});
```

- 針對==非同步==的錯誤發生且未處理時所產生的事件。

# 全局的錯誤封裝
```js
const handleErrorAsync = function handleErrorAsync(func) {
    // 1. 暫存 func 函式
    // 2. middleware 接住 router 資料
	// 3. router 將 req、res、next 傳入和執行
    return function (req, res, next) {
        // 4. 使用 catch 條件去捕捉錯誤
        func(req, res, next).catch(
            function (error) {
                return next(error);
            }
        );
    };
};

module.exports = handleErrorAsync;
```